{
 "title": "Video Metrics",
 "time": { "from": "now-20s", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "Exponential Weighted Moving Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "SELECT time, value FROM grafana.ewma"
    }
   ]
  },
  {
   "title": "Jitter History",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "SELECT time, value FROM grafana.jitter_hist"
    }
   ]
  },
  {
   "title": "Moving Variance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "SELECT time, value FROM grafana.moving_variance"
    }
   ]
  },
  {
   "title": "Standard Deviation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "SELECT time, value FROM grafana.std_dev"
    }
   ]
  },
  {
   "title": "Moving Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "SELECT time, value FROM grafana.mov_avg "
    }
   ]
  },
  {
   "title": "Delay History",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "SELECT time, value FROM grafana.delay_hist"
    }
   ]
  }
 ]
}